const product = [
  {
    id: "new01",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/newbook/1.jpg",
    title: "Tieng Vong Deo Khau Chia",
    category_id: 2,
    cost: 4.99,
  },
  {
    id: "new02",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/newbook/2.jpg",
    title: "Phuong Phap Jakarta",
    category_id: 2,
    cost: 4.99,
  },
  {
    id: "new03",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/newbook/3.jpg",
    title: "Cuon Sach Lon Ve Xe Co",
    category_id: 2,
    cost: 3.99,
  },
  {
    id: "new04",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/newbook/4.jpg",
    title: "Chuyen Em oc Sen Muon Biet Vi Sao No Cham Chap",
    category_id: 2,
    cost: 3.99,
  },
  {
    id: "new05",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/newbook/5.jpg",
    title: "Viet Nam Cua Toi",
    category_id: 2,
    cost: 5.99,
  },
  {
    id: "new06",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/newbook/6.jpg",
    title: "Tim Hieu Van Hoc Hien Dai Han Quoc",
    category_id: 2,
    cost: 3.99,
  },
  {
    id: "new07",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/newbook/7.jpg",
    title: "Kien Truc Nam Bo",
    category_id: 2,
    cost: 5.99,
  },
  {
    id: "new08",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/newbook/8.jpg",
    title: "Doi Ve Co Ban La Buon",
    category_id: 2,
    cost: 4.99,
  },
  {
    id: "new09",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/newbook/9.jpg",
    title: "Ngay Moi",
    category_id: 2,
    cost: 3.99,
  },
  {
    id: "new10",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/newbook/10.jpg",
    title: "Lich Su Cai Dep",
    category_id: 2,
    cost: 4.99,
  },

  {
    id: "child01",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/children/1.jpg",
    title: "To Mau 5",
    category_id: 3,
    cost: 2.99,
  },
  {
    id: "child02",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/children/2.jpg",
    title: "To Mau 6",
    category_id: 3,
    cost: 2.99,
  },
  {
    id: "child03",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/children/3.jpg",
    title: "Bo Da Tung Xa Con",
    category_id: 3,
    cost: 2.99,
  },
  {
    id: "child04",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/children/4.jpg",
    title: "Ngay Xua Cua Con",
    category_id: 3,
    cost: 3.99,
  },
  {
    id: "child05",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/children/5.jpg",
    title: "Me Cung Thu Vien",
    category_id: 3,
    cost: 3.99,
  },
  {
    id: "child06",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/children/6.jpg",
    title: "Minh Tu Ngu Ngoan",
    category_id: 3,
    cost: 2.99,
  },
  {
    id: "child07",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/children/7.jpg",
    title: "Cam On, Xin Loi",
    category_id: 3,
    cost: 3.99,
  },
  {
    id: "child08",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/children/8.jpg",
    title: "Ve Sinh Co The",
    category_id: 3,
    cost: 4.99,
  },
  {
    id: "child09",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/children/9.jpg",
    title: "Cham Me Om Met",
    category_id: 3,
    cost: 5.99,
  },
  {
    id: "child10",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/children/10.jpg",
    title: "Cung An Sinh Nhat",
    category_id: 3,
    cost: 2.99,
  },

  {
    id: "sci01",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/Science/1.jpg",
    title: "Chuyen Gia Kinh Te Buoc Vao Nha Tho",
    category_id: 4,
    cost: 4.99,
  },
  {
    id: "sci02",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/Science/2.jpg",
    title: "Luan Ve Yeu",
    category_id: 4,
    cost: 4.99,
  },
  {
    id: "sci03",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/Science/3.jpg",
    title: "AI Cho Marketing & Doi Moi San Pham",
    category_id: 4,
    cost: 5.99,
  },
  {
    id: "sci04",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/Science/4.jpg",
    title: "The Luong Nan Cua Nha Lanh Dao",
    category_id: 4,
    cost: 4.99,
  },
  {
    id: "sci05",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/Science/5.jpg",
    title: "Lich Trieu Tap Ky",
    category_id: 4,
    cost: 6.99,
  },
  {
    id: "sci06",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/Science/6.jpg",
    title: "Chuyen Phiem Su Hoc",
    category_id: 4,
    cost: 6.99,
  },
  {
    id: "sci07",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/Science/7.jpg",
    title: "Toi Tu Duy, Vay Thi Toi Ve",
    category_id: 4,
    cost: 3.99,
  },
  {
    id: "sci08",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/Science/8.jpg",
    title: "Heidegger Va Con Ha Ma Buoc Qua Cong Thien Duong",
    category_id: 4,
    cost: 5.99,
  },
  {
    id: "sci09",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/Science/9.jpg",
    title: "Cac The Gioi Song Song",
    category_id: 4,
    cost: 3.99,
  },
  {
    id: "sci10",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/Science/10.jpg",
    title: "How Business Works",
    category_id: 4,
    cost: 6.99,
  },

  {
    id: "foreign01",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhnn/1.jpg",
    title: "Tieng Nui",
    category_id: 5,
    cost: 3.99,
  },
  {
    id: "foreign02",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhnn/2.jpg",
    title: "Lam sao Dung Lai Thoi Gian",
    category_id: 5,
    cost: 4.99,
  },
  {
    id: "foreign03",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhnn/3.jpg",
    title: "Nhung Chuyen Tinh The Ky Moi",
    category_id: 5,
    cost: 3.99,
  },
  {
    id: "foreign04",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhnn/4.jpg",
    title: "Khong Ai Song Giong Ai Trong Cuoc Doi Nay",
    category_id: 5,
    cost: 4.99,
  },
  {
    id: "foreign05",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhnn/5.jpg",
    title: "Sang Trang",
    category_id: 5,
    cost: 2.99,
  },
  {
    id: "foreign06",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhnn/6.jpg",
    title: "Co Gai Mac Vay Tim",
    category_id: 5,
    cost: 2.99,
  },
  {
    id: "foreign07",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhnn/7.jpg",
    title: "Ai Tha Cac Than Ra?",
    category_id: 5,
    cost: 3.99,
  },
  {
    id: "foreign08",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhnn/8.jpg",
    title: "Ban Ve Am Nhac",
    category_id: 5,
    cost: 5.99,
  },
  {
    id: "foreign09",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhnn/9.jpg",
    title: "Ma Mau Tu",
    category_id: 5,
    cost: 3.99,
  },
  {
    id: "foreign10",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhnn/10.jpg",
    title: "Tam Hon Cao Thuong",
    category_id: 5,
    cost: 3.99,
  },

  {
    id: "vina01",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhvn/1.jpg",
    title: "Dam Tre Nhieu Van Hoa",
    category_id: 6,
    cost: 2.99,
  },
  {
    id: "vina02",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhvn/2.jpg",
    title: "Chua Dan",
    category_id: 6,
    cost: 3.99,
  },
  {
    id: "vina03",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhvn/3.jpg",
    title: "Bai Tho Cua Mot Nguoi Yeu Nuoc Minh",
    category_id: 6,
    cost: 2.99,
  },
  {
    id: "vina04",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhvn/4.jpg",
    title: "Muon Lam Nu Hoang, Dung yeu Nhu Hau Gai",
    category_id: 6,
    cost: 2.99,
  },
  {
    id: "vina05",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhvn/5.jpg",
    title: "Ky Tuc Xa Phong 307",
    category_id: 6,
    cost: 3.99,
  },
  {
    id: "vina06",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhvn/6.jpg",
    title: "Nguoi Dua Thu Tinh",
    category_id: 6,
    cost: 4.99,
  },
  {
    id: "vina07",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhvn/7.jpg",
    title: "Tham Kich Vi Nhan",
    category_id: 6,
    cost: 5.99,
  },
  {
    id: "vina08",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhvn/8.jpg",
    title: "Ve Nha",
    category_id: 6,
    cost: 3.99,
  },
  {
    id: "vina09",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhvn/9.jpg",
    title: "Lu Ruou Tran Gian",
    category_id: 6,
    cost: 3.99,
  },
  {
    id: "vina10",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/vhvn/10.jpg",
    title: "De Con Duoc Chich - Hieu Het Ve Vac Xin Va Mien Dich",
    category_id: 6,
    cost: 4.99,
  },

  {
    id: "nepo01",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/news_politics/1.jpg",
    title: "Linh Tron: Khoa Hoc La Ky Ve Loai Nguoi Trong Chien Tranh",
    category_id: 7,
    cost: 5.99,
  },
  {
    id: "nepo02",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/news_politics/2.jpg",
    title: "21 Bai Hoc Cho The Ky 21",
    category_id: 7,
    cost: 4.99,
  },
  {
    id: "nepo03",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/news_politics/3.jpg",
    title: "18 Phat Minh Vi Dai",
    category_id: 7,
    cost: 6.99,
  },
  {
    id: "nepo04",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/news_politics/4.jpg",
    title: "Luoc Su Ton Giao",
    category_id: 7,
    cost: 7.99,
  },
  {
    id: "nepo05",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/news_politics/5.jpg",
    title: "Biet An Noi Chang Lo Thua Thiet",
    category_id: 7,
    cost: 5.99,
  },
  {
    id: "nepo06",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/news_politics/6.jpg",
    title: "Tu Dien Chuc Quan Viet Nam",
    category_id: 7,
    cost: 6.99,
  },
  {
    id: "nepo07",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/news_politics/7.jpg",
    title: "Re Troi",
    category_id: 7,
    cost: 3.99,
  },
  {
    id: "nepo08",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/news_politics/8.jpg",
    title: "Toan Hoc: Mot Thien Tieu Thuyet",
    category_id: 7,
    cost: 5.99,
  },
  {
    id: "nepo09",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/news_politics/9.jpg",
    title: "Cach Moi Vat Van Hanh",
    category_id: 7,
    cost: 4.99,
  },
  {
    id: "nepo10",
    author: "Nguyen Thai Long",
    size: "14 x 20.5cm",
    image: "./img/news_politics/10.jpg",
    title: "Hoc Kieu My Tai Nha",
    category_id: 7,
    cost: 3.99,
  },
];
const categories = [
  {
    id: 2,
    name: "New",
    icon: "fa-solid fa-star",
  },
  {
    id: 3,
    name: "Children",
    icon: "fa-solid fa-child",
  },
  {
    id: 4,
    name: "Science",
    icon: "fa-brands fa-codepen",
  },
  {
    id: 5,
    name: "Foreign",
    icon: "fa-solid fa-f",
  },
  {
    id: 6,
    name: "Vietnamese",
    icon: "fa-solid fa-v",
  },
  {
    id: 7,
    name: "News and Politic",
    icon: "fa-solid fa-earth-america",
  },
];
